name: Bug Report
description: Report an unexpected behavior.
type: bug
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you aimed to do and expected to happen.
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Describe the unexpected behavior, with error codes and terminal logs if applicable.
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Describe a workaround, if there is one.
  - type: textarea
    id: impact
    attributes:
      label: Project Impact
      description: Describe how does this affect what you or others are working on.
  - type: input
    id: nargo-version
    attributes:
      label: Nargo Version
      description: Output from running `nargo --version`.
      placeholder: "e.g. 1.0.0-beta.20"
  - type: input
    id: noirjs-version
    attributes:
      label: NoirJS Version
      description: Version number of `noir_js` in `package.json`.
      placeholder: "e.g. 1.0.0-beta.20"
  - type: input
    id: backend-version
    attributes:
      label: Proving Backend
      description: The proving backend tooling and version used.
      placeholder: "e.g. Barretenberg bb 5.0.0-nightly.20260324"
  - type: dropdown
    id: pr_preference
    attributes:
      label: Would you like to submit a PR for this Issue?
      options:
        - "Maybe"
        - "Yes"
