name: Bug Report
description: Report an unexpected behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Description
        Thanks for taking the time to create the Issue, and welcome to the Noirot family!
  - type: textarea
    id: aim
    attributes:
      label: Aim
      description: Describe what you tried to achieve.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Describe the bug. Supply error codes / terminal logs if applicable.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Describe the steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
        4.
  - type: markdown
    attributes:
      value: |
        # Misc
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Specify the versions and environment details for which the issue is occurring.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Supplement further information if applicable.
  - type: markdown
    attributes:
      value: |
        # Pull Request
  - type: dropdown
    id: pr_preference
    attributes:
      label: Would you like to submit a PR for this Issue?
      description: Fellow contributors are happy to provide support where applicable.
      options:
        - "No"
        - "Maybe"
        - "Yes"
    validations:
      required: true
  - type: textarea
    id: pr_support
    attributes:
      label: Support Needs
      description: Support from other contributors you are looking for to create a PR for this Issue.
