name: Feature Request
description: Suggest an idea for this project.
type: enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe what you feel lacking, with code or examples if applicable.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Happy Case
      description: Describe how you think it should work, with pseudocode or examples if applicable.
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Describe workarounds, if any.
  - type: dropdown
    id: pr-preference
    attributes:
      label: Would you like to submit a PR for this Issue?
      multiple: false
      options:
        - "Maybe"
        - "Yes"
