name: Feature Request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create the Issue and welcome to the Noir community!
        # Description
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe what you feel lacking. Supply code / step-by-step examples if applicable.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Happy Case
      description: Describe how you think it should work. Supply pseudocode / step-by-step examples if applicable.
    validations:
      required: true
  - type: dropdown
    id: workaround
    attributes:
      label: Workaround
      description: Is there a workaround for this Issue? 
      options:
        - "Yes"
  - type: textarea
    id: workaround_description
    attributes:
      label: Workaround Description
      description: If yes, supplement how could the Issue be worked around.
  - type: input
    id: additional
    attributes:
      label: Additional Context
      description: Supplement further information if applicable.
  - type: markdown
    attributes:
      value: |
        # Impact
  - type: dropdown
    id: impact
    attributes:
      label: Project Impact
      description: How does this affect a project you or others are working on? 
      options:
        - "Nice-to-have"
        - "Blocker"
  - type: input
    id: blocker_context
    attributes:
      label: Blocker Context
      description: If a blocker, supplement how does this Issue affect the project.
  - type: markdown
    attributes:
      value: |
        # Pull Request
  - type: dropdown
    id: pr-preference
    attributes:
      label: Would you like to submit a PR for this Issue?
      description: Fellow contributors are happy to provide support where applicable.
      multiple: false
      options:
        - "Maybe"
        - "Yes"
  - type: input
    id: pr-support
    attributes:
      label: Support Needs
      description: Support from other contributors you are looking for to create a PR for this Issue.
